image: Previous Visual Studio 2017
init:
  - git config --global core.autocrlf true
  - SET DOTNET_CLI_TELEMETRY_OPTOUT=1
services:
  - mssql2016
  - mysql
  - postgresql96
install:
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build --configuration Release
before_test:
  - SET SQLSERVER_CONNECTION_STRING=Data Source=.;Initial Catalog=tempdb;Integrated Security=True
  - SET MYSQL_CONNECTION_STRING=server=localhost;uid=root;pwd=Password12!;database=yessql;
  - SET POSTGRESQL_CONNECTION_STRING=Server=localhost;Port=5432;Database=yessql;User Id=postgres;Password=Password12!;
  - SET MYSQL_PWD=Password12!
  - PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin;%PATH%
  - mysql -e "create database yessql;" --user=root
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - createdb yessql
test_script:
  - dotnet test .\test\YesSql.Tests\YesSql.Tests.csproj --filter "FullyQualifiedName~YesSql.Tests.PostgreSqlTests.ShouldIndexWithDateTime" --configuration Release  
