image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
services:
  - mssql2016
  - mysql
  - postgresql96
install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
  - ps: $env:NUGET_XMLDOC_MODE = "skip"
  - ps: $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
  - ps: Start-FileDownload 'https://dist.nuget.org/win-x86-commandline/latest/nuget.exe'
build_script:
  - dotnet --version
before_test:
  - SET SQLSERVER_CONNECTION_STRING=Data Source=.;Initial Catalog=tempdb;Integrated Security=True
  - SET MYSQL_CONNECTION_STRING=server=localhost;uid=root;pwd=Password12!;database=yessql;
  - SET POSTGRESQL_CONNECTION_STRING=Server=localhost;Port=5432;Database=yessql;User Id=postgres;Password=Password12!;
  - SET MYSQL_PWD=Password12!
  - PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin;%PATH%
  - mysql -e "create database yessql;" --user=root
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - createdb yessql
test_script:
  - dotnet test .\test\YesSql.Tests\YesSql.Tests.csproj --filter "FullyQualifiedName~YesSql.Tests.SqlServerTests" --configuration Release
  - dotnet test .\test\YesSql.Tests\YesSql.Tests.csproj --filter "FullyQualifiedName~YesSql.Tests.MySqlTests" --configuration Release
  - dotnet test .\test\YesSql.Tests\YesSql.Tests.csproj --filter "FullyQualifiedName~YesSql.Tests.SqliteTests" --configuration Release
  - dotnet test .\test\YesSql.Tests\YesSql.Tests.csproj --filter "FullyQualifiedName~YesSql.Tests.InMemoryTests" --configuration Release
  - dotnet test .\test\YesSql.Tests\YesSql.Tests.csproj --filter "FullyQualifiedName~YesSql.Tests.PostgreSqlTests" --configuration Release
  - dotnet test .\test\YesSql.Tests\YesSql.Tests.csproj --filter "FullyQualifiedName~YesSql.Tests.ProviderTests" --configuration Release
after_test:
  - dotnet pack -c Release
artifacts:
- path: 'src\**\*.nupkg'

deploy:  
  - provider: NuGet
    on:
      branch: dev
    server: https://www.myget.org/F/yessql/api/v2/package
    api_key:
      secure: 7PQvuxXn5P39X5QDlDKWbNpOKJKivpqkq7umakIirAZ12CSTAiCwjtJhSBGVboPm
    skip_symbols: true
    artifact: /.*\.nupkg/
  - provider: NuGet
    on:
      branch: master
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: 1W5p2uxA5pc/2pI0hkUkDbOukcM89CNTxENu8CKEAGFGtjJq1/2p+f0trkiipH6k
    skip_symbols: true
